const ComponentTypes = {
    GEOMETRY: 'GEOMETRY',
    DIRECTIONAL_LIGHT: 'DIRECTIONAL_LIGHT',
    STANDARD_MATERIAL: 'STANDARD_MATERIAL',
    TRANSFORM_3D: 'TRANSFORM_3D',
    PERSPECTIVE_CAMERA: 'PERSPECTIVE_CAMERA',
    ORTHOGRAPHIC_CAMERA: 'ORTHOGRAPHIC_CAMERA',
};

export default ComponentTypes;
